-- Insert initial shops list
INSERT INTO public.shops (shop_name, category) VALUES 
('10067 - GOIKO CC ALLEGRA', 'Cafeterías y restaurantes'),
('10670 ARROYOMOLINOS XANAD', 'Compras (otros)'),
('108 - LA VAGUADA CC ALCAM', 'Supermercados y alimentación'),
('A TODAS HORAS', 'Cafeterías y restaurantes'),
('A.D. VILLA ROSA', 'Deporte y gimnasio'),
('AB SERVICIOS SELECTA E', 'Supermercados y alimentación'),
('ABDERAHMAN', 'Cafeterías y restaurantes'),
('ACCIONA MOTOSHARING', 'Taxis y Carsharing'),
('ACCOR* NOVOTEL RESORT', 'Hotel y alojamiento'),
('ACEITUNAS SANCHEZ', 'Supermercados y alimentación'),
('ACOSTA PELUQUERIA', 'Belleza, peluquería y perfumería'),
('ACTIVIDADES CULTURALES WE', 'Cine, teatro y espectáculos'),
('ADIANTUM', 'Dentista, médico'),
('ADM LOTERIAS 378', 'Loterías y apuestas'),
('ADMON LOTERIA 16', 'Loterías y apuestas'),
('ADMON. DE LOTERIA NR 1-CA', 'Loterías y apuestas'),
('ADOLFO DOMINGUEZ', 'Ropa y complementos'),
('AELIA VIRGIN ESTACION MAL', 'Compras (otros)'),
('AHORRAMAS SA', 'Supercercados y alimentación'),
('AIRBNB * HM9CANDNPA', 'Hotel y alojamiento'),
('AIRBNB * HMSWX5BCHW', 'Hotel y alojamiento'),
('ALCAMPO28029-VAGUADA', 'Supermercados y alimentación'),
('ALDI HORTALEZA', 'Supermercados y alimentación'),
('ALDI MADRID TDA 25', 'Supermercados y alimentación'),
('ALDI VALDEBEBAS', 'Supermercados y alimentación'),
('ALEHOP 297 ADIF ESTAC. C', 'Regalos y juguetes'),
('ALIMENTACI/N SHUIHONG JI', 'Supermercados y alimentación'),
('ALIMENTACION', 'Supermercados y alimentación'),
('ALIMENTACION HAIMIAO', 'Supermercados y alimentación'),
('ALIMENTACION LIU MINPING', 'Supermercados y alimentación'),
('ALIMENTACION SHUIHONG JIA', 'Supermercados y alimentación'),
('ALIMERCA JOSE LUIS HERN', 'Supermercados y alimentación'),
('ALQUERIA DEL BROSQUIL', 'Cafeterías y restaurantes'),
('ALSA INTERNET', 'Billetes de viaje'),
('ALVARO MORENO', 'Compras (otros)'),
('AMAZON* 1G2VE6EN5', 'Compras (otros)'),
('AMAZON* 1T6K905U5', 'Compras (otros)'),
('AMAZON* 404-0430536-10', 'Compras (otros)'),
('Amazon Prime*UD8KR9GT5', 'Compras (otros)'),
('AMZN Mktp ES', 'Compras (otros)'),
('ANAFE Y CARBON', 'Cafeterías y restaurantes'),
('ANTOJITOS PERUANOS', 'Cafeterías y restaurantes'),
('AOSSA GLOBAL SL', 'Deporte y gimnasio'),
('AP-1 ARABAT ZARA-ETXA', 'Peajes'),
('APARC VICENTE INGLADA', 'Parking y garaje'),
('APARCAMIENTO J. BENAVENTE', 'Parking y garaje'),
('APPLE.COM/BILL', 'Libros, música y videojuegos'),
('APP CRTM', 'Transporte público'),
('ARKOSE          2970176', 'Deporte y gimnasio'),
('ASIA CENTER', 'Supermercados y alimentación'),
('AUCHAN CHASSENE 4798580', 'Supermercados y alimentación'),
('AUTOMOCION GAR.MORENO', 'Gasolina y combustible'),
('AYTO MADRID DEPORTES', 'Pago de impuestos'),
('Amazon.es*3M4MB6WG5', 'Compras (otros)'),
('BAR A.D. VILLA ROSA', 'Cafeterías y restaurantes'),
('BAR ALUPA TERRAZA', 'Cafeterías y restaurantes'),
('BAR AS DE COPAS', 'Cafeterías y restaurantes'),
('BARBERIA STIILS', 'Belleza, peluquería y perfumería'),
('BEN & JERRYûS HELADERIA X', 'Cafeterías y restaurantes'),
('BENETTON OUTLET MAD', 'Ropa y complementos'),
('BENGAL DONNER KEBAB', 'Cafeterías y restaurantes'),
('BK31035 VALDEBEBAS', 'Cafeterías y restaurantes'),
('BKG*HOTEL AT BOOKING.C', 'Hotel y alojamiento'),
('BOLT.EU/O/2501171816', 'Taxis y Carsharing'),
('BOOKING.COM', 'Hotel y alojamiento'),
('BRIEF ATOCHA', 'Cafeterías y restaurantes'),
('Cabify ES 2440c4YUBoHI', 'Taxis y Carsharing'),
('CAFETERIA FARIGOLA', 'Cafeterías y restaurantes'),
('CAIXAFORUM MADRID', 'Cine, teatro y espectáculos'),
('CALZE OUTLET SSREYES O053', 'Ropa y complementos'),
('CARREF HORTALEZA', 'Supermercados y alimentación'),
('CARREFOUR CITY  2142836', 'Supermercados y alimentación'),
('CASA BRIYAN', 'Cafeterías y restaurantes'),
('CEDIPSA 05459-1 DIGES CUA', 'Gasolina y combustible'),
('CENTRO MEDICO', 'Dentista, médico'),
('CEPSA 07405-1 E.S SAN MAT', 'Gasolina y combustible'),
('CERVECERIA JUSTO III', 'Cafeterías y restaurantes'),
('CESIGRAL APARCAMIENTOS', 'Parking y garaje'),
('CHEVERE', 'Cafeterías y restaurantes'),
('CHURRERIA AGUSTINA', 'Cafeterías y restaurantes'),
('COFFEE AND CAKE', 'Cafeterías y restaurantes'),
('COSTCO WHOLESALE SPAIN, S', 'Supermercados y alimentación'),
('CRUNCHYROLL.COM', 'Ocio y viajes (otros)'),
('DECATHLON DEHESA', 'Deporte y gimnasio'),
('DENLI KEBAB', 'Cafeterías y restaurantes'),
('DGT TASAS JEFATURAS 2', 'Pago de impuestos'),
('DIA 14184', 'Supermercados y alimentación'),
('DOMINO''S PIZZA', 'Cafeterías y restaurantes'),
('EDREAMS', 'Ocio y viajes (otros)'),
('EL CORTE INGLES PINTOR SO', 'Compras (otros)'),
('EL MANABA MADRID', 'Cafeterías y restaurantes'),
('EMT VALENCIA', 'Transporte público'),
('ESTANCO SANTA VIRGILIA', 'Compras (otros)'),
('EVEREST TANDOORI', 'Cafeterías y restaurantes'),
('FARMACIA ANA E CASTRILLO', 'Dentista, médico'),
('FIVE GUYS SPAIN SL', 'Cafeterías y restaurantes'),
('FNAC MAJADAHONDA', 'Libros, música y videojuegos'),
('FREENOW* BCU9WX-2', 'Taxis y Carsharing'),
('FRUTAS ANGELES MONTERO', 'Supermercados y alimentación'),
('GARAJE CENTRO', 'Parking y garaje'),
('GO SUSHING ARTURO SORIA', 'Cafeterías y restaurantes'),
('GOOGLE *YouTube Videos', 'Electrónica'),
('HM ES0043', 'Ropa y complementos'),
('HOSPITAL LA MOR', 'Dentista, médico'),
('HOTEL LOS ANGELES', 'Hotel y alojamiento'),
('IBERIA CS   1430992943', 'Billetes de viaje'),
('IKEA SSDLR FOOD', 'Cafeterías y restaurantes'),
('IRISH ROVER', 'Cine, teatro y espectáculos'),
('KIKO MILANO', 'Belleza, peluquería y perfumería'),
('KLIK PELUQUEROS', 'Belleza, peluquería y perfumería'),
('LA DESPENSA HORTALEZA', 'Supermercados y alimentación'),
('LECLERC ANGLETDACVL', 'Supermercados y alimentación'),
('LEFTIES', 'Ropa y complementos'),
('LIDL MAD-BUCARAMANGA', 'Supermercados y alimentación'),
('LLAO LLAO LA VAGUADA', 'Cafeterías y restaurantes'),
('MAKRO ALCOBENDAS', 'Supermercados y alimentación'),
('MCDONALD,S TGN', 'Cafeterías y restaurantes'),
('MEDIA MARKT ONLINE', 'Electrónica'),
('MERCADONA CC.PLENILUNIO', 'Supermercados y alimentación'),
('METRO DE MADRID S.A.', 'Transporte público'),
('NETFLIX.COM', 'Ocio y viajes (otros)'),
('NORMAL MADRID LA VAGUADA', 'Ropa y complementos'),
('OFICINA PLAZA CASTILLA', 'Compras (otros)'),
('OH MY CUT', 'Belleza, peluquería y perfumería'),
('ONCE', 'Loterías y apuestas'),
('OUIGO Espana', 'Billetes de viaje'),
('OYSHO', 'Ropa y complementos'),
('PANADERIA', 'Cafeterías y restaurantes'),
('PARFOIS', 'Ropa y complementos'),
('PARKING AUGUSTO FIGUEROA', 'Parking y garaje'),
('PAYPAL *EASYPARK', 'Parking y garaje'),
('PERFUMERIA PRIMOR', 'Belleza, peluquería y perfumería'),
('PINTXOTERAPIA', 'Cafeterías y restaurantes'),
('PRIMARK LA VAGUADA', 'Ropa y complementos'),
('Prime Video', 'Ocio y viajes (otros)'),
('RATP', 'Transporte público'),
('REAL DONAR KEBAB', 'Cafeterías y restaurantes'),
('RENFE VIAJEROS APP', 'Transporte público'),
('RESTAURANTE DAVANTI', 'Cafeterías y restaurantes'),
('SEPHORA COSMETICOS', 'Belleza, peluquería y perfumería'),
('SFERA C.C PLAZA NORTE', 'Ropa y complementos'),
('SKYSHOWTIME 333E0 Estanda', 'Ocio y viajes (otros)'),
('SNCF VOYAGEURS', 'Transporte público'),
('TABERNA 7', 'Cafeterías y restaurantes'),
('TAXI GRANADA LIC 0499', 'Taxis y Carsharing'),
('TELEPIZZA GRANVIA', 'Cafeterías y restaurantes'),
('THE BEST SHAVE BARBER', 'Belleza, peluquería y perfumería'),
('TIGER SS.RR. - C.C. PLAZA', 'Regalos y juguetes'),
('UBER   *TRIP', 'Taxis y Carsharing'),
('VEEPEE', 'Compras (otros)'),
('VIPS VALDEBEBAS', 'Cafeterías y restaurantes'),
('ZARA', 'Ropa y complementos'),
('ZARA HOME', 'Ropa y complementos');